groups:
  - name: company-of-one-alerts
    rules:
      # High-level service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} has been down for more than 5 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.instance }}"

      # Memory and resource alerts
      - alert: HighMemoryUsage
        expr: (nodejs_memory_heap_used_bytes / nodejs_memory_heap_total_bytes) * 100 > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% on {{ $labels.instance }}"

      - alert: CriticalMemoryUsage
        expr: (nodejs_memory_heap_used_bytes / nodejs_memory_heap_total_bytes) * 100 > 95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 95% on {{ $labels.instance }}"

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 20% on {{ $labels.instance }}"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk space"
          description: "Disk space is below 10% on {{ $labels.instance }}"

      # Application-specific alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.instance }}"

      - alert: ProcessRestarts
        expr: increase(nodejs_process_uptime_seconds[1h]) < 3600
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Process has restarted"
          description: "Process on {{ $labels.instance }} has restarted recently"

      # Deployment and version alerts
      - alert: DeploymentFailed
        expr: rate(deployment_failures_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Deployment failed"
          description: "Deployment has failed on {{ $labels.instance }}"

      # Business logic alerts
      - alert: NoTrafficReceived
        expr: rate(http_requests_total[5m]) == 0
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "No traffic received"
          description: "No HTTP requests received on {{ $labels.instance }} for 15 minutes"

  - name: infrastructure-alerts
    rules:
      # Container and Docker alerts
      - alert: ContainerKilled
        expr: time() - container_last_seen > 60
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container killed"
          description: "Container {{ $labels.name }} has been killed"

      - alert: ContainerCpuUsage
        expr: (sum by (container_label_com_docker_compose_service) (rate(container_cpu_usage_seconds_total[3m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container CPU usage"
          description: "Container {{ $labels.container_label_com_docker_compose_service }} CPU usage is above 80%"

      - alert: ContainerMemoryUsage
        expr: (sum by (container_label_com_docker_compose_service) (container_memory_working_set_bytes) / sum by (container_label_com_docker_compose_service) (container_spec_memory_limit_bytes) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container Memory usage"
          description: "Container {{ $labels.container_label_com_docker_compose_service }} Memory usage is above 80%"

  - name: external-service-alerts
    rules:
      # External service monitoring
      - alert: ExternalServiceDown
        expr: probe_success == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "External service is down"
          description: "External service {{ $labels.instance }} has been down for more than 5 minutes"

      - alert: SlowExternalService
        expr: probe_duration_seconds > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "External service is slow"
          description: "External service {{ $labels.instance }} is responding slowly ({{ $value }}s)"